version: '3'

services:
  nginx:
    container_name: nuxtnginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 81:80
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
  # laravelのアプリケーションが入っている
    container_name: nuxtphp
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
      - composer-volume:/var/www/php/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    working_dir: /var/www/html
  #    command: 'php artisan serve --host 0.0.0.0'

  mysql:
    # mysqlの設定
    #.envのhost名＝dockerのコンテ名
    container_name: nuxtmysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nuxtsunctum
      MYSQL_USER: nuxtsunctum
      MYSQL_PASSWORD: nuxtsunctum
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
#  node:
#    image: node:9
#    volumes:
#      - .:/app
#      - node-modules-volume:/app/node_modules
#    working_dir: '/app'
volumes:
  composer-volume:
  mysql-volume:
  node-modules-volume:
